version: '3.8'

services:
  simulator:
    build: .
    container_name: data-simulator
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s 